### ISSUE TITLE
Upload Artifact to Maven Central

### ISSUE THREAD

**Issue by lewisheadden** [mesosphere/marathon-client#14]
It would be great to have this officially supported client in Maven Central rather than trying to work out which other forks of mohitsoni have the latest features. 

Requested here: https://twitter.com/rogerignazio/status/710188771585695745

**Comment by afraisse** [comment]
+1, maven dependency given in readme doesn't resolve (com.mesosphere.marathon-clien:0.1.0)

**Comment by titosand** [comment]
Hi all, I've updated the README - let me know if this helps!

**Comment by rji** [comment]
@colin-msphere, @ssk2 – I believe the plan was to upload this to Maven Central, which is why I asked @lewisheadden to create this ticket here (so we didn't lose track of it). Do you guys know when we might get around to publishing this? It looks like this issue already has 7 upvotes, so people definitely want it 😄

**Comment by rji** [comment]
Ah, it looks like @titosand and I posted around the same time here. @lewisheadden, @afraisse – will using our Maven repo (versus Maven Central) work for you?

**Comment by afraisse** [comment]
This totally works for us ! Thanks.

**Comment by ssk2** [comment]
Great! @lewisheadden - please re-open this issue if Maven central is a strict requirement. Otherwise, I think we're all set.

**Comment by gazal-k** [comment]
Getting the following error in [marathon-maven-plugin](https://github.com/holidaycheck/marathon-maven-plugin)

```sh
[ERROR] Failed to execute goal on project marathon-maven-plugin: Could not resolve dependencies for project com.holidaycheck:marathon-maven-plugin:maven-plugin:0.0.4-SNAPSHOT: Failed to collect dependencies at com.mesosphere:marathon-client:jar:0.2.0: Failed to read artifact descriptor for com.mesosphere:marathon-client:jar:0.2.0: Could not transfer artifact com.mesosphere:marathon-client:pom:0.2.0 from/to downloads.mesosphere.com (https://downloads.mesosphere.com/maven/): Received fatal alert: handshake_failure -> [Help 1]
```

Any help would be much appreciated.

**Comment by krystiannowak** [comment]
@rji Might make sense to use Maven central repo especially when e.g. Maven plugins being already there https://github.com/holidaycheck/marathon-maven-plugin would also like to use it - see @gazal-k 's https://github.com/holidaycheck/marathon-maven-plugin/pull/8 . So if possible, please reopen the ticket and propagate the library into Maven central - if there are no obstacles of course - we would be grateful.

**Comment by ssk2** [comment]
@krystiannowak - will do. We're planning to do this for other plugins too.

@gazal-k - did you get this resolved?

**Comment by krystiannowak** [comment]
@ssk2 Great! And thanks!

**Comment by gazal-k** [comment]
@ssk2 nop, still getting the same SSL issue.

**Comment by ssk2** [comment]
@gazal-k - I've tried to replicate locally both using the pom in [your branch](https://github.com/gazal-k/marathon-maven-plugin/tree/marathon-client-update) and using the [Marathon plugin](https://github.com/jenkinsci/marathon-plugin/blob/master/pom.xml) and both build find. Wondering if this has been fixed already. @colin-msphere - could you try and replicate this with an `mvn package`?

**Comment by krystiannowak** [comment]
Not sure if that helps, but building the plugin directly from https://github.com/gazal-k/marathon-maven-plugin/tree/marathon-client-update works for me.

**Comment by gazal-k** [comment]
Not sure why, but had the problem on my work laptop. Worked just fine on my personal laptop. Sorry for the trouble.

**Comment by titosand** [comment]
Hi all, marathon-client:0.2.1 is now available in Maven Central, I've updated the README.md accordingly. Will close this issue unless there is anything else! :)

**Comment by krystiannowak** [comment]
@titosand great news - now we can use this dependency without additional repository links :)
