### ISSUE TITLE
Incorrect type for Task.state on DeleteAppTask(s)Response

### ISSUE THREAD

**Issue by AntonOfTheWoods** [mesosphere/marathon-client#72]
Task.state is a String. Except when you call /v2/apps/{app_id}/tasks/{task_id}, and it has the following structure:
...
        "state": {
            "activeSince": "2017-09-24T09:55:20.681Z",
            "condition": {
                "str": "running"
            },
            "since": "2017-09-24T09:55:20.681Z"
        },
...

And so we get the following error:

Exception in thread "main" feign.codec.DecodeException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1316 path $.task.state

My java is seriously rusty and I confess I don't understand how feign works under the hood but one very naive option (that works!) is simply to have two Task objects - DeleteTask and StandardTask with different kinds of state properties. I will submit a PR but I'm fairly confident it will be too ugly to accept...

**Comment by AntonOfTheWoods** [comment]
See https://github.com/mesosphere/marathon-client/pull/73

**Comment by timcharper** [comment]
@AntonOfTheWoods This looks like a bug with the API. It looks like we are using the wrong formatter for that endpoint.

Merging your patch to deal with either is probably sensible, but, what we should really do is fix the API to be in alignment with what is specified.

**Comment by timcharper** [comment]
@AntonOfTheWoods what would you think if we modified the client to ignore these failures? Or, can you momentarily intercept serialization exceptions and ignore for the time being? I'd personally vote to not to make marathon-client consume a format that was never intended to be exposed to the outside world.

**Comment by timcharper** [comment]
I have filed issue https://jira.mesosphere.com/browse/MARATHON-7811 for fixing Marathon

**Comment by AntonOfTheWoods** [comment]
Thanks for checking this out @timcharper . I certainly understand your point of view, and I accept that you don't want to add a kludge. So I will add a kludge in my code until MARATHON-7811 gets fixed and a new version published. Might it be a good idea to have tests in marathon to make sure that what the raml says is what actually happens to catch any other cases like this now and in the future?
